on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build:
      runs-on: ubuntu-latest
      permissions:
          contents: write
      steps:
          - name: Check out repository
            uses: actions/checkout@v4
  
          - name: Set up Quarto
            uses: quarto-dev/quarto-actions/setup@v2
            with:
              version: '1.5.57' # Specify the desired version

          - name: Render Quarto Project
            uses: quarto-dev/quarto-actions/render@v2

          - name: Upload static files as artifact
            uses: actions/upload-pages-artifact@v3
            with:
              path: docs/

  # Deployment job
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
